Page admin Backers : Problème de performance
MTES-MCT/aides-territoires pull request #194
Opened 2020-10-02 14:24 UTC by lazybird

Il y avait un problème avec la page admin des porteur d'aides.

2020-10-02 14:38 UTC, thibault requested changes

2020-10-02 14:38 UTC, thibault commented on src/backers/admin.py
> +    readonly_fields = ('display_related_aids',)
Nickel, je n'aurais pas pensé à utiliser `readonly_fields`.

2020-10-02 14:38 UTC, thibault commented on src/backers/admin.py
> +        for aid in obj.financed_aids.all():
Sur un porteur avec beaucoup d'aides, ça devient très difficile de s'y retrouver. Je pense que ça serait un vrai plus d'avoir un tri des aides par ordre alphabetique.

2020-10-02 14:38 UTC, thibault commented on src/backers/admin.py
> +            related_aid_html += '<br/> * '
Peut-être que ce serait sémantiquement plus correct d'utiliser `ul` et `li` ?

2020-10-02 14:38 UTC, thibault requested changes
Le tri par ordre alphabetique me semble important.

Passer par une liste serait sympa, mais pas bloquant pour la fusion.

2020-10-02 15:02 UTC, lazybird commented on src/backers/admin.py
> +            related_aid_html += '<br/> * '
ok

2020-10-02 15:02 UTC, lazybird commented on src/backers/admin.py
> +        for aid in obj.financed_aids.all():
ok

2020-10-02 15:08 UTC, thibault commented on src/backers/admin.py
> +            related_aid_html += f'<li><a href="{url}">'
C'est vraiment super cool d'avoir intégré un lien.

J'ai la sensation qu'on gagnerait beaucoup en lisibilité avec une seule fonction `format`, qu'en penses-tu ?

```
format('<li><a href="{url}">{name}</></li>', {
…
}) ?
```

Si besoin, [django fournit une fonction format_html](https://docs.djangoproject.com/fr/3.1/ref/utils/#django.utils.html.format_html) pour gérer les échappements.

2020-10-02 15:09 UTC, thibault commented
Par ailleurs, je crois qu'il y un problème de style car le build est cassé.

2020-10-02 15:09 UTC, SarahRubio approved these changes

2020-10-05 13:30 UTC, thibault approved these changes
Il y a juste le petit problème de pep8 qui casse le build, sinon c'est ok pour moi :+1:

2020-10-05 13:54 UTC, merged