Créer des alertes à partir d'un fichier csv d'emails
MTES-MCT/aides-territoires pull request #217
Opened 2020-10-22 08:13 UTC by raphodn

Management command pour créer des alertes à partir d'une liste d'emails (csv avec une colonne `emails`)

2020-11-06 09:14 UTC, lazybird commented on src/alerts/management/commands/create_alerts_from_csv_file.py
> +            send_alert_confirmation_email.delay(alert.email, alert.token)
Donc si je comprends bien, on va envoyer des emails de confirmation. Est-ce qu'il y a un délais de réponse / expiration du lien de confirmation ?

2020-11-17 15:51 UTC, raphodn commented on src/alerts/management/commands/create_alerts_from_csv_file.py
> +            send_alert_confirmation_email.delay(alert.email, alert.token)
Je ne sais pas trop, je réutilise la task `send_alert_confirmation_email` qui a l'air de se baser uniquement sur le token de l'alerte pour la validation

2020-11-18 09:06 UTC, thibault requested changes
Rien à dire sur le code.

Par contre, j'ai quelques réticences au niveau de la légalité, et en fonction de la volumétrie attendue, il semble qu'on pourrait prendre plus de précautions pour éviter de spammer des utilisateurs.

Enfin, comme le script semble amené à être réutilisé, il me semble qu'il manque les tests unitaires.

2020-11-18 09:06 UTC, thibault commented on src/alerts/management/commands/create_alerts_from_csv_file.py
> +        if alert_validated:
Je n'ai pas suivi l'origine de la demande ni la discussion, mais j'ai quelques questions sur cette validation.

Le RGPD nous contraint à recueillir et conserver la trace d'un consentement explicite avant de stocker et utiliser des adresses individuelles.

Le fait que les adresses soient opt-in chez le partenaire ne lui donne pas le droit de les transférer chez nous sauf si cela a été consenti explicitement. De même, ça ne nous donne pas le droit de les récupérer pour les utiliser à notre guise.

Est-ce que vous vous êtes assurés d'être bien dans la légalité ? Si c'est le cas, avez-vous correctement documenté l'origine du consentement ?

2020-11-18 17:21 UTC, raphodn commented on src/alerts/management/commands/create_alerts_from_csv_file.py
> +        print(alert_date_created)
en effet je l'ai oublié ! ca serait top d'avoir un linter qui passe derrière nous ;)

2020-11-18 17:23 UTC, raphodn commented on src/alerts/management/commands/create_alerts_from_csv_file.py
> +        with open(csv_path) as csv_file:
Je peux regarder, mais si toutes les alertes sont créées en même temps, ca posera problème pour l'envoi d'email dans la foulée non ? ou alors faire décaler leur `date_created`

2020-11-19 08:13 UTC, thibault commented on src/alerts/management/commands/create_alerts_from_csv_file.py
> +        print(alert_date_created)
Il y a effectivement un linter lancé par Travis, mais il n'interdit pas les instructions `print`. On pourrait le rajouter.

2020-11-27 12:02 UTC, raphodn commented
J'ai fait quelques modifications : 
- les alertes sont crées en bulk, en utilisant une transaction
- ajout de tests pour chacun des arguments de la commande
- les valeurs des champs par défaut de l'alerte sont gérés par le modèle, plus par la commande

2020-11-30 09:10 UTC, thibault approved these changes

2020-11-30 14:31 UTC, merged