Problème d'image non affichée quand on la redimensionne
MTES-MCT/aides-territoires pull request #258
Opened 2020-11-19 01:24 UTC by lazybird

À propos du bug :
- La source du problème est décrit ici : https://github.com/Alex-D/Trumbowyg/issues/1158
- Le tag `img` est parfois transformé en tag `canvas`. Ça ne devrait déjà pas arriver.
- En plus, comme nous avons un cleanup-backend des tags avant la sauvegarde, le tag `canvas` disparaît tout simplement.

Ma proposition pour avancer : 

> - I have imported a copy of the resizimg JS plugin
> - Instead of loading the upstream version, I'm using that local version of the plugin.
> - This is a temporary fix and we should get back to using upstream once the fix is released.

J'ai mis un message dans le dépôt GIT de Trumbowyg pour motivé l'application du patch et une nouvelle release.

2020-11-19 08:25 UTC, thibault requested changes
C'était vraiment un problème tordu. Tu as dû t'arracher les cheveux.

2020-11-19 08:25 UTC, thibault commented on src/dataproviders/utils.py
> +ALLOWED_ATTRS = ['href', 'src', 'alt', 'width', 'height', 'style']
Aïe aïe aïe ! Les attributs `style` sont les plus importants à supprimer durant les imports.

En effet, nous importons beaucoup de contenu avec de grosses quantités de styles en ligne, et si on ne les supprime pas, Aides-territoires ressemble très vite à un sapin de Noël.

Peut-être qu'on pourrait modifier la fonction pour avoir un comportement différent en fonction des permissions de l'utilisateur (être plus permissifs pour les admins, par exemple) ?

2020-11-19 13:00 UTC, lazybird commented on src/dataproviders/utils.py
> +ALLOWED_ATTRS = ['href', 'src', 'alt', 'width', 'height', 'style']
Oui on pourrait faire ça alors, plus de flexibilité pour les admins.

2020-11-20 09:11 UTC, lazybird commented on src/dataproviders/utils.py
> +ALLOWED_ATTRS = ['href', 'src', 'alt', 'width', 'height', 'style']
@thibault : j'ai fait une modif pour que dans le contexte où le cleanup est fait dans la classe TextField, on accepte : 
- les attributs `style` 
- les tags `img`

Et donc, dans le contexte où le cleanup est appliqué dans les scripts d'import, `style` et `img` serait retiré.

Je ne sais pas trop comment le tester.

2020-11-20 14:09 UTC, thibault approved these changes

2020-11-23 05:43 UTC, merged