Portefeuille d'aides : nouvelle colonne périmètre
MTES-MCT/aides-territoires pull request #320
Opened 2020-12-14 16:57 UTC by raphodn

https://trello.com/c/HtAr5f9O/840-portefeuille-daide-affichage-p%C3%A9rim%C3%A9tres
https://trello.com/c/9sxm8ayV/842-portefeuille-daide-titre-aide

Modifications apportées : 
- Nouvelle colonne qui affiche le périmètre de l'aide, avec possibilité d'ordonner par cette colonne
- Afficher le Nom complet de l'aide, donc il y aura parfois un retour à la ligne
- La largeur de la colonne Nom est fixée à 50%

![Screenshot 2020-12-14 at 16 26 29](https://user-images.githubusercontent.com/7147385/102110723-cc7f0f80-3e35-11eb-831f-28fbb9a9b8b4.png)

2020-12-14 18:04 UTC, SarahRubio commented on src/templates/aids/draft_list.html
> +                <th title="{{ _('Order by') }} {{ _('Aid title') }}" width="50%">{% sortable_header _('Aid title') 'name' %}</th>
Est-ce qu'il ne faudrait pas rapatrier le style dans le fichier css et ajouter ici une class ou un id?

2020-12-14 18:07 UTC, SarahRubio commented on src/templates/aids/draft_list.html
> +                <th title="{{ _('Order by') }} {{ _('Aid title') }}" width="50%">{% sortable_header _('Aid title') 'name' %}</th>
Tu peux peut être élargir la `div main-content` dans ce cas-ci pour que la colonne "modifié le" s'affiche sur une seule ligne ?

2020-12-14 18:07 UTC, raphodn commented on src/templates/aids/draft_list.html
> +                <th title="{{ _('Order by') }} {{ _('Aid title') }}" width="50%">{% sortable_header _('Aid title') 'name' %}</th>
ah oui c'est vrai, je corrige. merci

2020-12-14 18:13 UTC, SarahRubio approved these changes

2020-12-15 08:53 UTC, thibault requested changes
Rien à dire sur le code, nickel.

Je trouve qu'on pourrait gagner en élégance sur le design du tableau.

![image](https://user-images.githubusercontent.com/11499/102192301-e31b7a00-3eba-11eb-98f0-d332d3cac976.png)

Autant il est normal et inévitable qu'on laisse des retours à la ligne pour le nom de l'aide ou le périmètre, autant ça me nuire à la lisibilité sur les autres colonnes qui contiennent des données courtes.

Je pense qu'il serait utile d'appliquer la propriété `white-space: nowrap` aux entêtes des colonnes, ainsi qu'aux valeurs courtes, notamment l'échéance et le statut.

2020-12-15 08:53 UTC, thibault commented on src/static/css/_custom.scss
> +            width: 50%;
Je ne comprends pas l'intention derrière cette ligne. Puisque la colonne « name » est la plus longue, pourquoi ne pas laisser le navigateur lui allouer toute la place disponible ?

Si c'est pour éviter d'avoir toujours des retours à la ligne sur les autres colonnes, cela ne suffira pas toujours, cf. cet exemple :

![image](https://user-images.githubusercontent.com/11499/102192185-b8312600-3eba-11eb-8c20-e3e6fad2fdf6.png)

2020-12-15 09:44 UTC, raphodn commented on src/static/css/_custom.scss
> +            width: 50%;
merci pour ton feedback, je vais tester avec du style additionnel 👍

2020-12-15 09:54 UTC, raphodn commented
J'ai pushé une modif additionnel qui prend en compte l'ensemble de vos commentaires (merci !)
- pas de saut de ligne dans le header du tableau
- pas de saut de ligne dans les colonnes Echance et Statut
- pas de width spécifique pour la colonne Nom

![Screenshot 2020-12-15 at 10 54 32](https://user-images.githubusercontent.com/7147385/102199459-f3842280-3ec3-11eb-9bab-5a98e23defad.png)

2020-12-15 10:13 UTC, thibault approved these changes

2020-12-15 11:17 UTC, merged