Porteurs d'aides : ajout de champs meta pour le SEO
MTES-MCT/aides-territoires pull request #338
Opened 2021-01-04 17:22 UTC by raphodn

https://trello.com/c/26394nkJ/849-ajouter-un-champ-meta-title-sur-les-pages-porteurs-admin

Modifications apportées : 
- ajout des champs `meta_title` et `meta_description` au modèle Backer
- ajoute backer.meta_title & backer.meta_description dans le header de la page porteur
- ajout des champs `date_created` au modèles Backer & BackerGroup (pour mieux suivre l'évolution de leur nombre)
- fix des traductions qui avaient été en partie supprimé pendant le rebase/merge de https://github.com/MTES-MCT/aides-territoires/pull/333/files

2021-01-05 08:38 UTC, thibault requested changes
La page « partenaire » semble ne plus fonctionner plus chez moi.

Sinon, nickel.

2021-01-05 08:38 UTC, thibault commented on src/templates/backers/detail.html
> +{% endif %}
La page « partenaire » plante chez moi, il semble à cause de cette ligne.

2021-01-05 10:49 UTC, raphodn commented on src/templates/backers/detail.html
> +{% endif %}
ok merci je regarde ! j'avais commencé à regarder, et j'ai eu des soucis, du coup je viens de faire https://github.com/MTES-MCT/aides-territoires/pull/339 par dessus 😅

2021-01-05 10:59 UTC, raphodn commented on src/templates/backers/detail.html
> +{% endif %}
oops c'était un `{% endblock %}` qui manquait. finalement je vais enlever ce extra_head, on verra dans un second temps les meta spécifiques de cette page niveau open graph

2021-01-05 13:43 UTC, thibault approved these changes

2021-01-08 10:24 UTC, lazybird commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter un champ Meta / title sur les pages porteurs (admin)](https://trello.com/c/26394nkJ/849-ajouter-un-champ-meta-title-sur-les-pages-porteurs-admin)

2021-01-08 10:43 UTC, merged