Ajout des thématiques et programmes associés sur les pages Porteur.
MTES-MCT/aides-territoires pull request #342
Opened 2021-01-06 09:21 UTC by SarahRubio

Première partie de la carte https://trello.com/c/lbNwvDST/843-fiche-porteur-en-admin-sur-at-affichage-des-th%C3%A9matiques-des-aides.

Permet l'affichage sur chaque page porteur, des thématiques, catégories et programmes associées aux aides de ce porteur.

- Dans le fichier `backers/views.py`, ajout d'une `def get_context` pour récupérer les thématiques, catégories et programmes associés aux aides du porteur.
- Dans le fichier `templates/backers/detail.html`, ajout d'une section pour l'affichage des thématiques, catégories et programmes.
- Ajout du style dans le fichier `_custom.scss`

2021-01-06 11:36 UTC, SarahRubio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fiche porteur sur AT / Affichage des thématiques des aides](https://trello.com/c/lbNwvDST/843-fiche-porteur-sur-at-affichage-des-th%C3%A9matiques-des-aides)

2021-01-06 13:21 UTC, thibault requested changes

2021-01-06 13:21 UTC, thibault commented on src/backers/views.py
> +        aids = Aid.objects.open().published() \
Pour info uniquement : il existe un raccourci : `Aid.objecst.live()`.

2021-01-06 13:21 UTC, thibault commented on src/backers/views.py
> +            .prefetch_related(Prefetch('categories', queryset=categories_list))
Excellent d'avoir pensé à `Prefetch`.

2021-01-06 13:21 UTC, thibault commented on src/backers/views.py
> +            categories_by_theme[theme] = [k for k in list_themes.keys() if list_themes[k] == theme]
Il m'a fallu un effort pour comprendre ce qui se passe ici. Je pense qu'en pourrait obtenir le même résultat d'une manière moins alambiquée et plus lisible.

Tu pourrais par exemple trier ta `queryset` : `order_by('categories__theme__name', 'categories__name')` et dans le template, utiliser l'opérateur [regroup](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#regroup)

2021-01-06 13:21 UTC, thibault commented on src/backers/views.py
> +        programs = Aid.objects.open().published() \
Une variable `programs` qui contient des aides, il y a anguille sous roche :)

Plus sérieusement, ce code ne me semble pas optimal : chez moi, la page du porteur Ademe génère 37 requêtes et le programme « France relance » est affiché plusieurs fois.

Une requête alternative pourrait être :

```suggestion
        programs = Program.objects \
            .filter(aids__in=aids) \
            .exclude(logo__isnull=True) \
            .exclude(logo='') \
            .distinct()
```

2021-01-06 13:21 UTC, thibault commented on src/static/css/_custom.scss
> +    max-height: 120px;
C'est une idée en l'air mais si cette même limite de hauteur est utilisée à plusieurs endroits dans le css, il pourrait être pertinent d'en faire une variable dans le fichier `_theme.scss`

2021-01-06 13:21 UTC, thibault commented on src/templates/backers/detail.html
> +                <h2>Présentation générale :</h2>
Pour respecter la nomenclature utilisée sur les autres templates, il faudrait éviter les textes en français mais passer par une balise de traduction. Dans la mesure ou il s'agit d'un titre, les deux points « : » ne sont pas nécessaires.

2021-01-06 13:39 UTC, SarahRubio commented on src/backers/views.py
> +            categories_by_theme[theme] = [k for k in list_themes.keys() if list_themes[k] == theme]
J'avais bien essayé de passer par l'opérateur `regroup` mais j'avais beaucoup de doublons de thématiques car le `regroup `dépendait d'une boucle sur les aides et ne regroupait donc les catégories par thème que pour une même aide. Je retente quelque chose. :)

2021-01-06 13:40 UTC, SarahRubio commented on src/static/css/_custom.scss
> +    max-height: 120px;
Oui je pense que j'aurais dû faire ça depuis un petit moment! :) Merci pour ta suggestion.

2021-01-08 07:58 UTC, thibault approved these changes
C'est vraiment beaucoup plus lisible en l'état :+1:

2021-01-12 13:55 UTC, merged