Affichage des Themes, catégories et programmes sur les pages porteurs-admin
MTES-MCT/aides-territoires pull request #371
Opened 2021-01-18 15:02 UTC by SarahRubio

https://trello.com/c/vgag6uNB/882-affichage-des-th%C3%A9matiques-categories-et-programmes-sur-la-page-admin-porteur

Dans l'admin, ajout des thématiques, categories et programmes sur les page porteurs.

2021-01-18 15:03 UTC, SarahRubio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Affichage des thématiques, categories et programmes sur la page Admin/porteur](https://trello.com/c/vgag6uNB/882-affichage-des-th%C3%A9matiques-categories-et-programmes-sur-la-page-admin-porteur)

2021-01-19 10:03 UTC, thibault requested changes

2021-01-19 10:03 UTC, thibault commented on src/backers/admin.py
> +        categories_list = Category.objects \
Il y a un problème dans la récupération des données. En effet, quand j'affiche la page d'admin d'un porteur, je constate 80 requêtes SQL envoyées, ce qui dégrade les performances.

D'une manière générale, on fait rarement moins d'une dizaine de requêtes mais au dessus de 20, l'impact sur les performances commence vraiment à se faire sentir.

Sauf erreur de ma part, je pense que tu pourrais récupérer toutes les données nécessaires en une seule requête, sans faire de détours.

```suggestion
        categories = Category.objects \
            .select_related('theme') \
            .order_by('theme__name', 'name') \
            .filter(aids__financers=obj) \
            .values_list('theme__name', 'name') \
            .distinct()
        themes = groupby(categories, operator.itemgetter(0))

        related_themes_html = format_html('<ul>')
        for theme, theme_categories in themes:
            related_themes_html += format_html(
                '<li><strong>{theme} > </strong>',
                theme=theme)

            for _, theme_category in theme_categories:
                related_themes_html += format_html(
                    '{category}. ',
                    category=theme_category)
            related_themes_html += format_html('<li>')
        related_themes_html += format_html('</ul>')
        return related_themes_htm
```

Fonctionnellement, on retombe sur nos pattes. Par contre, seules les aides financées sont prises en compte (`financed_aids`), pas les aides instruites (`instructed_aids`), est-ce voulu ?

2021-02-04 10:39 UTC, lazybird approved these changes

2021-02-04 10:42 UTC, merged