Ajout d'un bouton "voir plus" pour afficher tous les résultats d'aides
MTES-MCT/aides-territoires pull request #404
Opened 2021-02-01 15:01 UTC by SarahRubio

2021-02-01 17:32 UTC, SarahRubio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Infinite scroll sur page de résultat](https://trello.com/c/DPKG5Uio/893-infinite-scroll-sur-page-de-r%C3%A9sultat)

2021-02-02 09:38 UTC, thibault commented
Hello @SarahRubio,

Voici mes commentaires et suggestions sur l'état actuel de la PR.

Le premier constat, c'est que ça marche et c'est quand même un bon premier point \o/

Je pense que ton intuition est la bonne en utilisant ajax pour ré-appeler la même url avec un paramètre « page » différent et en ajoutant directement le html à l'existant.

Pour info, au début d'AT, la recherche fonctionnait aussi en ajax et c'était fait comme ça.

Une autre solution possible aurait été de se baser sur l'API, mais ça nous aménerait à passer par js pour formatter du html à partir de résultats json, et ce serait inutilement compliqué pour un bénéfice à peu près nul.

Voici maintenant les points sur lesquels je pense qu'il reste du travail.

D'abord, il y a un principe important qui est que **javascript ne devrait servir que pour de l'amélioration progressive**. Ça veut dire que ton script doit améliorer un comportement existant mais ne doit pas être nécessaire au fonctionnement du site.

En l'état actuel des choses :
  - si je désactive js
  - si j'utilise un navigateur spécial qui n'en dispose pas
  - si je suis un bot google
  - si une erreur réseau m'empêche de télécharger jquery
  - si un bug dans un script fait planter ton script…
  
…je ne peux tout simplement plus naviguer dans les résultats, et c'est bloquant.

Ce n'est pas toujours possible ou facile (par exemple, je pense qu'en désactivant js, certains champs de recherche ne fonctionnent plus), mais c'est un objectif à garder en tête.

Il faut donc **laisser la pagination existante en place**, et effectuer tous les changements depuis un script.

 - s'il y a des modifications du dom à effectuer (remplacer les liens de pagination par un bouton), on le fait dans le script ;
 - s'il y a des événements à intercepter, on le fait depuis le script, etc ;
 
Autre truc à garder en tête : quand on modifie le fonctionnement « normal » du web, on doit être attentif à ce que les fonctionnalités du navigateur continuent à fonctionner normalement.

Par exemple, si je clique trois fois sur « voir plus », navigue sur le détail d'une aide puis clique sur « retour arrière », je dois trouver mes résultats comme je les avais laissé.

De même, si je clique trois fois sur « voir plus » et bookmarque l'url, je dois retrouver les mêmes résultats en rechargeant la page.

Si je clique dix fois frénétiquement sur « voir plus », je ne dois pas avoir dix fois les mêmes aides ajoutées à la page actuelle.

Sinon, ça veut dire qu'on a perdu des fonctionnalités pour un bénéfice pas forcément évident à la base.

Conséquence : implémenter ce type de navigation en ajax est *toujours* plus compliqué que prévu et il faut *toujours* insister sur le coût en vérifiant que le besoin est *vraiment* au rendez-vous :)

Je te propose de fouiller dans l'historique du projet en récupérant le commit `280d2e62`.

> git checkout 280d2e62

Tu pourra alors regarder le contenu du fichier `src/static/js/aids/dynamic_search_engine.js`. C'est le code du moteur de recherche à l'époque ou les résultats étaient récupérés en ajax, qui est loin d'être parfait mais te donnera peut-être des idées.

À ta dispo si tu veux en discuter ou si tu as des questions.

2021-02-02 09:39 UTC, thibault commented on src/templates/_pagination.html
> -        {% if page_obj.has_previous %}
Attention ! le fichier `_pagination.html` est un template générique qui n'est pas utilisé que pour les aides. En le modifiant, tu risque de casser d'autres sections du site.

2021-02-02 09:42 UTC, thibault commented on src/templates/_pagination.html
> +<script>
Je sais que la PR est en chantier, donc je ne détaille pas trop mes commentaires. Pour info, il faut éviter les scripts en ligne, chaque script doit aller dans un fichier dédié.

En effet, c'est plutôt une bonne pratique de définir des [entêtes csp](https://developer.mozilla.org/fr/docs/Web/HTTP/CSP) qui bloquent l'exécution de scripts en ligne, ce qui fait que ton code marcherait en local mais plus sur un environnement de production.

2021-02-02 09:46 UTC, thibault commented on src/templates/_pagination.html
> +                $('.aids').append($(html_parsed).find(".aids > .col"))
Ça peut suffire de filtrer le résultat, mais ça risque d'avoir un impact sur l'efficacité de récupérer toute la page.

Une technique courante consiste à utiliser un template différent dans la vue en fonction du type de requête (ajax ou non).

Dans la vue, on peut [surcharger get_template_names](https://ccbv.co.uk/projects/Django/3.0/django.views.generic.list/ListView/#get_template_names) pour renvoyer un template différent dans les deux cas.

On peut [utiliser is_ajax](https://docs.djangoproject.com/fr/3.1/ref/request-response/#django.http.HttpRequest.is_ajax) pour vérifier s'il s'agit d'une requête ajax ou non.

On peut alors créer un nouveau template qui n'affiche que les résultats, ou carrément ré-utiliser `_results.html`.

2021-02-02 09:47 UTC, thibault commented on src/templates/aids/_base_search.html
> +<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
Idem, j'imagine que c'est temporaire. Pour info, jquery est déjà intégré dans la page (cf. `_base.html`).

Pour des raisons de respect de la vie privée, on ne peut pas se baser sur des cdn appartenant à google :)

2021-02-08 14:10 UTC, thibault requested changes
Hello @SarahRubio,

Tu as bien avancé. La fonctionnalité marche, la logique est bonne.

Il reste quelques petits problèmes au niveau de l'organisation du code, et un ou deux cas limites à prendre en compte, et ça sera bon :)

2021-02-08 14:10 UTC, thibault commented on src/static/js/aids/show_more.js
> +        searchParams = url.searchParams
J'ai des doutes quant à la compatibilité de cette fonctionnalité.

Par exemple, `searchParams` ne semble pas supporté par Safari : https://developer.mozilla.org/fr/docs/Web/API/URL#browser_compatibility

Les données concernant Edge sont également incertaines.

As-tu effectué des tests sur ces navigateurs ?

2021-02-08 14:10 UTC, thibault commented on src/static/js/aids/show_more.js
> +                beforeSend: function () {
Ici, il y a un cas limite problématique : si un utilisateur clique furieusement sur le bouton plusieurs fois, tu vas lancer plusieurs requêtes ajax.

Les requêtes sont correctes (le numéro de page est bien incrémenté), mais il n'est pas garanti que les résultats soient insérés dans l'ordre.

Il faudrait peut-être songer à désactiver le bouton le temps que la requête ne termine ?

2021-02-08 14:10 UTC, thibault commented on src/static/js/aids/show_more.js
> +    last_page = $(".last")[0].href
Il existe un cas limite dans lequel ton script plante, c'est quand on essaye de charger la dernière page de résultats.

Exemple : https://aides-territoires-pr404.osc-fr1.scalingo.io/aides/?integration=&apply_before=&perimeter=&text=ademe&order_by=relevance&action=search&page=4

Dans ce cas là, il n'y a pas d'élément `a` dans le lien `.last`. Le rajouter peut être une solution facile.

2021-02-08 16:54 UTC, SarahRubio commented on src/templates/_pagination.html
> +            <div id="show_more_btn">
Ma première idée était aussi de mettre un `button` mais comme à l'intérieur il me faut des `div` pour le `spinner` je crois qu'il ne serait pas valide en html de mettre un button.

2021-02-09 10:28 UTC, SarahRubio commented on src/static/js/aids/show_more.js
> +        searchParams = url.searchParams
Je me suis appuyé sur https://caniuse.com/?search=url . J'ai retesté hier sur Safari cela semble bon. J'aurai par contre bien besoin d'un testeur pour Edge et pour Internet Explorer.

2021-02-09 13:46 UTC, thibault approved these changes
Hello. J'ai suggéré une dernière piste d'amélioration, mais c'est du pinaillage. Super boulot, c'est ok pour moi.

2021-02-09 13:46 UTC, thibault commented on src/static/js/aids/show_more.js
> +            $('#show_more').removeClass('d-none')
Quand on arrive sur la dernière page, le bouton « voir plus d'aides » reste en place, et ne disparaît que lorsqu'on re-clique dessus.

Il me semble que ce serait plus pertinent de masquer le bouton automatiquement lorsqu'on atteint la dernière page.

2021-02-10 12:44 UTC, merged