Refonte du formulaire de publication d'une aide
MTES-MCT/aides-territoires pull request #433
Opened 2021-02-12 19:39 UTC by SarahRubio

https://trello.com/c/lq33is3Q/941-refonte-du-formulaire-de-cr%C3%A9ation-%C3%A9dition-dune-aide

2021-02-13 08:21 UTC, SarahRubio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refonte du formulaire de création / édition d'une aide](https://trello.com/c/lq33is3Q/941-refonte-du-formulaire-de-cr%C3%A9ation-%C3%A9dition-dune-aide)

2021-02-22 10:04 UTC, thibault requested changes
Hello,

La nouvelle mise en page est vraiment top. Ça rend le formulaire beaucoup plus lisible et utilisable.

Le bug de z-index qui empêche de donner le focus au formulaire est bloquant, car il empêche l'édition de fonctionner.

Les autres commentaires concernent des points de détail qui empêchent le design de paraître complètement « pro ».

Sinon, c'est nickel.

2021-02-22 10:04 UTC, thibault commented on src/static/css/_custom.scss
> +    div.sidebar-actions {
![image](https://user-images.githubusercontent.com/11499/108692552-0ab34200-74fd-11eb-83ea-fdbc1d2143ad.png)

Sur écran mobile, l'ombre du formulaire principale s'étend vers le haut sur les boîtes. C'est un peu contraire à ce qu'on trouve partout ailleurs sur le site ou l'ombre est toujours portée vers le bas.

2021-02-22 11:43 UTC, SarahRubio commented on src/static/css/_custom.scss
> +        z-index: -1;
Je suis bien contente que tu es revue cette PR. Merci d'avoir repéré ce bug. 

Si je supprime complétement le z-index, un petit bug apparaît (la barre d'outil rich-text-field a je pense un index fort car au scroll du formulaire elle apparaît par dessus la barre de navigation). J'ai augmenté l'index de la barre de navigation et mis un index positif pour le formulaire. :)

2021-03-02 09:23 UTC, lazybird approved these changes

2021-03-02 09:29 UTC, merged