Création d'un formulaire de contact
MTES-MCT/aides-territoires pull request #526
Opened 2021-03-26 16:05 UTC by raphodn

2021-03-26 16:05 UTC, raphodn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Création d'un formulaire de contact](https://trello.com/c/ynJi8DkU/1029-cr%C3%A9ation-dun-formulaire-de-contact)

2021-04-07 07:59 UTC, thibault requested changes

2021-04-07 07:59 UTC, thibault commented on src/home/urls.py
> +    path('contact/', ContactView.as_view(), name='contact'),
Peut-être ajouter la balise i18n pour la cohérence globale, même si la traduction est effectivement identique ?

```suggestion
    path(_('contact/'), ContactView.as_view(), name='contact'),
```

2021-04-07 07:59 UTC, thibault commented on src/templates/home/contact.html
> +                <h1>Nous contacter</h1>
Il faudra rediscuter de l'utilisation de l'anglais et du français dans le code. Ça ne me pose pas de soucis si on décide de se passer de balise de traduction dans les templates, mais il faudrait garder une cohérence sur l'ensemble du code.

2021-04-07 07:59 UTC, thibault commented on src/templates/home/contact.html
> +                    <div class="col col-md-6">
Il y a un petit soucis de rendu sur les tailles d'écran intermédiaires.

![image](https://user-images.githubusercontent.com/11499/113830003-73d9d680-9786-11eb-91b7-caa0254ceae1.png)

Nous avons un style de page étroit qu'on utilise généralement pour les formulaires simples. Ça peut peut-être être intéressant de le réutiliser ?

(Par exemple https://aides-territoires.beta.gouv.fr/comptes/profil-contributeur/)

2021-04-07 07:59 UTC, thibault commented on src/templates/home/contact.html
> +                <div class="row">
Si le formulaire est en colonne, pourquoi avoir utilisé plusieurs balises `row` ?

2021-04-07 07:59 UTC, thibault commented on src/templates/home/contact.html
> +                be processed <a href="{{ legal_mentions_url }}" target="_blank">
Certes, mais la liste des traitements sur la page des mentions légales doit aussi être mise à jour pour inclure la fonctionnalité de formulaire de contact :)

2021-04-07 07:59 UTC, thibault commented on src/home/forms.py
> +        ('contact_add', 'En savoir plus sur l\'ajout de vos aides sur la plateforme'),  # noqa
Peut-être garder une cohérence sur la formulation du sujet ?

 - Je rencontre un problème technique sur le site
 - Je veux en savoir plus sur l'ajout…

2021-04-07 07:59 UTC, thibault commented on src/home/views.py
> +        send_contact_form_email.delay(form_dict)
Il est très probable que nous mangions très rapidement une tonne de spam de la part de bots.

On a eu le problème quand on avait un formulaire d'inscription à la newsletter. J'ai aussi eu le problème sur un autre site.

Une technique que j'ai testé et qui marche étonnamment bien est de mettre en place un champ « pot de miel », qui reste facultatif et caché via css. Si le champ est rempli, c'est forcément que la soumission vient d'un bot.

On peut attendre que le problème se pose effectivement, mais je parie que ça ne prendra pas trop longtemps.

2021-04-07 09:01 UTC, raphodn commented on src/templates/home/contact.html
> +                <h1>Nous contacter</h1>
Il faut qu'on en discute oui, on l'a évoqué comme piste avec les autres il y a quelques semaines.

2021-04-07 09:20 UTC, raphodn commented on src/templates/home/contact.html
> +                    <div class="col col-md-6">
En effet, c'etait voulu par John, mais je vais plutot opter pour le formulaire etroit je pense

2021-04-07 09:22 UTC, raphodn commented on src/home/views.py
> +        send_contact_form_email.delay(form_dict)
Je suis partant pour faire du "wait & see" en effet. On a déjà notre email en mailto sur le site, ainsi que notre numéro de téléphone, donc je ne sais pas si on va être véritablement spammé d'avantage qu'actuellement.

2021-04-09 07:00 UTC, raphodn commented on src/home/urls.py
> +    path('contact/', ContactView.as_view(), name='contact'),
(ignoré car on ne fait plus l'effort de traduire)

2021-04-09 07:00 UTC, raphodn commented on src/templates/home/contact.html
> +                <h1>Nous contacter</h1>
(ignoré car on ne fait plus l'effort de traduire)

2021-04-09 07:01 UTC, raphodn commented on src/templates/home/contact.html
> +                be processed <a href="{{ legal_mentions_url }}" target="_blank">
Vu qu'il y a des champs optionnels, je ne sais pas exactement quoi mettre ? Je met tous les champs ? Et vu que les infos sont envoyées sur Slack, ca complique la chose il me semble...

2021-04-12 07:17 UTC, raphodn commented on src/templates/home/contact.html
> +                    <div class="col col-md-6">
je suis passé au formulaire étroit

2021-04-12 07:34 UTC, thibault commented on src/templates/home/contact.html
> +                be processed <a href="{{ legal_mentions_url }}" target="_blank">
S'il y a des champs optionnels, il faut les mentionner.

Si on renvoie les données personnelles des utilisateurs vers les serveurs d'une boîte aux US, il faut très explicitement le mentionner dans la liste des traitements :) Il faut aussi qu'on se pose la question de ce que devienne ces données ensuite : combien de temps on les conserve ? comment on fait si les utilisateurs demandent leur suppression ?

2021-04-12 15:13 UTC, raphodn commented
@thibault j'ai pushé des modifs avec les mentions légales + enlevé Slack, on verra dans une PR suivante

2021-04-15 16:37 UTC, merged